# packages in environment at /home/jhubinon/miniforge3/envs/workshop:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2025.1.31            hbcca054_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_4    conda-forge
libblas                   3.9.0           31_h59b9bed_openblas    conda-forge
libcblas                  3.9.0           31_he106b2a_openblas    conda-forge
libffi                    3.4.6                h2dba641_1    conda-forge
libgcc                    14.2.0               h767d61c_2    conda-forge
libgcc-ng                 14.2.0               h69a702a_2    conda-forge
libgfortran               14.2.0               h69a702a_2    conda-forge
libgfortran5              14.2.0               hf1ad2bd_2    conda-forge
libgomp                   14.2.0               h767d61c_2    conda-forge
liblapack                 3.9.0           31_h7ac8fdf_openblas    conda-forge
liblzma                   5.8.1                hb9d3cd8_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.29          pthreads_h94d23a6_0    conda-forge
libsqlite                 3.49.1               hee588c1_2    conda-forge
libstdcxx                 14.2.0               h8f9b012_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
ncurses                   6.5                  h2d0b736_3    conda-forge
numpy                     2.0.2            py39h9cb892a_1    conda-forge
openssl                   3.5.0                h7b32b05_0    conda-forge
pandas                    2.2.3            py39h3b40f6f_2    conda-forge
pip                       25.0.1             pyh8b19718_0    conda-forge
python                    3.9.21          h9c0c6dc_1_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_1    conda-forge
python-tzdata             2025.2             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      6_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8c095d6_2    conda-forge
setuptools                78.1.0             pyhff2d567_0    conda-forge
six                       1.17.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2025b                h78e105d_0    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
