# packages in environment at /home/jhubinon/miniforge3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
archspec                  0.2.5              pyhd8ed1ab_0    conda-forge
asgiref                   3.8.1                    pypi_0    pypi
bleach                    6.2.0                    pypi_0    pypi
boltons                   24.0.0             pyhd8ed1ab_1    conda-forge
brotli-python             1.1.0           py312h2ec8cdc_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.4               hb9d3cd8_0    conda-forge
ca-certificates           2025.1.31            hbcca054_0    conda-forge
certifi                   2025.1.31          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h06ac9bb_0    conda-forge
charset-normalizer        3.4.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
conda                     24.11.3         py312h7900ff3_0    conda-forge
conda-libmamba-solver     24.9.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.4.0              pyh7900ff3_2    conda-forge
conda-package-streaming   0.11.0             pyhd8ed1ab_1    conda-forge
distro                    1.9.0              pyhd8ed1ab_1    conda-forge
django                    5.1.5                    pypi_0    pypi
django-contrib-comments   2.2.0                    pypi_0    pypi
django-cors-headers       4.3.1                    pypi_0    pypi
django-cte                1.3.2                    pypi_0    pypi
django-filter             24.3                     pypi_0    pypi
django-json-widget        1.1.1                    pypi_0    pypi
django-lazy-services      0.0.3                    pypi_0    pypi
django-ltree              0.5.3                    pypi_0    pypi
django-sql-dashboard      1.2                      pypi_0    pypi
django-storages           1.14.2                   pypi_0    pypi
django-translated-fields  0.12.0                   pypi_0    pypi
django-webpack-loader     3.1.1                    pypi_0    pypi
djangorestframework       3.15.2                   pypi_0    pypi
djangorestframework-csv   3.0.2                    pypi_0    pypi
djangorestframework-simplejwt 5.3.1                    pypi_0    pypi
drf-yasg                  1.21.7                   pypi_0    pypi
et-xmlfile                2.0.0                    pypi_0    pypi
fmt                       11.0.2               h434a139_0    conda-forge
frozendict                2.4.6           py312h66e93f0_0    conda-forge
future                    1.0.0                    pypi_0    pypi
h2                        4.2.0              pyhd8ed1ab_0    conda-forge
hpack                     4.1.0              pyhd8ed1ab_0    conda-forge
hyperframe                6.1.0              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
inflection                0.5.1                    pypi_0    pypi
jsonpatch                 1.33               pyhd8ed1ab_1    conda-forge
jsonpointer               3.0.0           py312h7900ff3_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_4    conda-forge
libarchive                3.7.7                h4585015_3    conda-forge
libcurl                   8.12.1               h332b0f4_0    conda-forge
libedit                   3.1.20250104    pl5321h7949ede_0    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.6                h2dba641_0    conda-forge
libgcc                    14.2.0               h767d61c_2    conda-forge
libgcc-ng                 14.2.0               h69a702a_2    conda-forge
libgomp                   14.2.0               h767d61c_2    conda-forge
libiconv                  1.18                 h4ce23a2_1    conda-forge
liblzma                   5.6.4                hb9d3cd8_0    conda-forge
libmamba                  1.5.12               h49b8a8d_0    conda-forge
libmambapy                1.5.12          py312hbaee817_0    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsolv                   0.7.30               h3509ff9_0    conda-forge
libsqlite                 3.49.1               hee588c1_1    conda-forge
libssh2                   1.11.1               hf672d98_0    conda-forge
libstdcxx                 14.2.0               h8f9b012_2    conda-forge
libstdcxx-ng              14.2.0               h4852527_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.13.6               h8d12d68_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lz4-c                     1.10.0               h5888daf_1    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
mamba                     1.5.12          py312h9460a1c_0    conda-forge
markdown                  3.7                      pypi_0    pypi
menuinst                  2.2.0           py312h7900ff3_0    conda-forge
ncurses                   6.5                  h2d0b736_3    conda-forge
nested-multipart-parser   1.5.0                    pypi_0    pypi
numpy                     2.2.4                    pypi_0    pypi
openpyxl                  3.1.5                    pypi_0    pypi
openssl                   3.4.1                h7b32b05_0    conda-forge
packaging                 24.2               pyhd8ed1ab_2    conda-forge
pandas                    2.2.3                    pypi_0    pypi
pip                       25.0.1             pyh8b19718_0    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_1    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_1    conda-forge
psycopg2-binary           2.9.10                   pypi_0    pypi
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py312h66e93f0_2    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pyjwt                     1.7.1                    pypi_0    pypi
pysocks                   1.7.1              pyha55dd90_7    conda-forge
python                    3.12.9          h9e4cc4f_1_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python_abi                3.12                    5_cp312    conda-forge
pytz                      2025.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h8c095d6_2    conda-forge
reproc                    14.2.5.post0         hb9d3cd8_0    conda-forge
reproc-cpp                14.2.5.post0         h5888daf_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_1    conda-forge
ruamel.yaml               0.18.10         py312h66e93f0_0    conda-forge
ruamel.yaml.clib          0.2.8           py312h66e93f0_1    conda-forge
ruff                      0.9.7                    pypi_0    pypi
setuptools                75.8.2             pyhff2d567_0    conda-forge
six                       1.17.0                   pypi_0    pypi
sqlparse                  0.5.3                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_1    conda-forge
truststore                0.10.1             pyh29332c3_0    conda-forge
tzdata                    2025.2                   pypi_0    pypi
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   2.3.0              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zstandard                 0.23.0          py312hef9b889_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
